version: "3"
services:
  database:
    image: mysql
    container_name: wanted_db
    environment:
      - MYSQL_DATABASE= wanted_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - wanted_db
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    container_name: wanted_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: "@Master123"
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - wanted_db

networks:
  wanted_db: