spring:
    profiles:
        include: secret
        active: local

    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                show_sql: true